### ISSUE TITLE
Bei anmeldung wird die Seite nicht gefunden

### ISSUE THREAD

**Issue by segeberger** [tkrebs/ep3-bs#12]
Nach der Instalation, will ich mich als Admin anmelden, bekomme aber die anzeige das die seite nicht gefunden werden kann. Fehler 404. Woran kann das liegen?
Auch wenn ich einen neuen User registrieren will ist das so.

**Comment by tkrebs** [comment]
Das Apache-Modul "mod_rewrite" muss serverseitig installiert und eingerichtet sein damit die Software korrekt funktionieren kann.

**Comment by segeberger** [comment]
Das Apache-Modul ist instaliert. Ich nutze 1und1 als Webhosting das ist das schon instaliert. Und einrichten? In der .htacces datei? Danke für die Antwort :-)

**Comment by tkrebs** [comment]
Bei 1&1 hilft es oft, in der .htaccess-Datei die führende Raute in Zeile 4 zu entfernen:

#RewriteBase /   # Try to uncomment this if you experience redirect problems

**Comment by segeberger** [comment]
Ne leider hilft das nicht dann bekomme ich diese Fehlermeldung:
nternal Server Error

The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator, and inform them of the time the error occurred, and anything you might have done that may have caused the error.

More information about this error may be available in the server error log.

Additionally, a 404 Not Found error was encountered while trying to use an ErrorDocument to handle the request.

**Comment by segeberger** [comment]
So habe die # entfernt. jetzt geht die Weiterleitung nur erscheint kein Eingabefeld. Als ob da was mit der adresse nicht stimmt.

**Comment by bruxi** [comment]
Ich habe das gleiche Problem und habe schon in der .htaccess in Zeile 4 auch die RewriteBase / auskommentiert.
Ich erhalte due Fehlermeldung "The requested URL /svrg/user/registration was not found on this server."

**Comment by zaeng** [comment]
Gleiches Problem. Zeitweise funktiert was, aber dann geht die Weiterleitung nicht mehr.

**Comment by tkrebs** [comment]
Im Zweifelsfall hilft der Webserver-Anbieter weiter, da die mod_rewrite-Konfiguration von Anbieter zu Anbieter unterschiedlich sein kann.

Abgesehen davon ist darauf zu achten, dass das Buchungssystem unter einer Top-Level- oder Sub-Domain läuft, denn dafür ist die mitgelieferte .htaccess-Datei ausgerichtet. Ansonsten müssen ggf. Pfadangaben manuell korrigiert werden.

**Comment by zaeng** [comment]
mod_rewrite ist bei 1+1 wohl kein Problem, ist an. 

Kann man die .htaccess nochmal irgendwo getrennt bekommen, die habe ich wohl dann falsch mit den Angaben aus dem GitHub überschrieben ;-) In welchen Ordner kommt sie? Man sieht die Pfadangaben ja leider nicht..

Danke für die schnelle Hilfe. 

Henry

Tobias Krebs schrieb:

**Comment by MichaelAlthoff** [comment]
Hallo, der Thread ist zwar schon etwas älter aber ich habe ein ähnliches Problem.
Nach einer neuen Installation der Version 1.6 ist soweit alles eingerichtet. Die .zip Datei habe ich im Web-Root entpackt. Ich komme auch auf die Seite und sehe den Kalender. Also sollte soweit alles in Ordnung sein was die Einrichtung angeht. mod_rewrite ist auch aktiv. 
Mein Problem ist nun dass ich sobald ich etwas anklicke, oder mich anmelden möchte bekomme ich Error 404. Z.B. wenn ich auf ein Zeitfeld klicke versucht er auf public/square etwas zu finden.
Oder wenn ich mich anmelden möchte will er zu /public/user/login......     aber auch da 404.
Da ich davon ausgehe dass das rewrite funktioniert kann ich mir das nicht erklären.
Die Verzeichnisse gibt es in diesem Pfad nicht.
Laufen tut die Sache auf Ubuntu16.04.Server, aktuellem PHP, 
Vielleicht hat jemand eine Idee woran das liegen kann und mir bei der Sache helfen.
Vielen Dank ...
LG
Mike

**Comment by tkrebs** [comment]
Versuche mal testweise, die komplette Datei

`/public/.htaccess`

mit folgendem Inhalt zu ersetzen:

```
<IfModule mod_rewrite.c>

    RewriteEngine On

    RewriteRule ^(favicon\.ico)$ imgs-client/icons/fav.ico [L]
    RewriteRule ^(robots\.txt)$ misc/$1 [L]

    RewriteCond %{REQUEST_FILENAME} -s [OR]
    RewriteCond %{REQUEST_FILENAME} -l [OR]
    RewriteCond %{REQUEST_FILENAME} -d
    RewriteRule ^.*$ - [NC,L]

    RewriteCond %{REQUEST_URI}::$1 ^(/.+)(.+)::\2$
    RewriteRule ^(.*) - [E=BASE:%1]
    RewriteRule ^(.*)$ %{ENV:BASE}index.php [NC,L]

</IfModule>
```

**Comment by MichaelAlthoff** [comment]
Hallo,
leider hat das nicht geholfen. Ich habe nach wie vor das gleiche Problem.
Kann ich noch irgendwelche Infos posten die die Fehlersuche etwas vereinfachen ?
Vielen Dank für die Hilfe.
LG Mike

**Comment by tkrebs** [comment]
Versuche noch mal, folgende Zeile

`RewriteEngine On`

folgendermaßen zu ergänzen

```
RewriteEngine On
RewriteBase /
```

Ansonsten wirklich nochmal kontrollieren ob das Apache mod_rewrite-Modul installiert und aktiviert ist.

**Comment by MichaelAlthoff** [comment]
Ich wollte mich noch mal melden.
Das Problem ist behoben und der Fehler saß mal wieder vor dem PC.
mod_rewrite war wie geschrieben aktiv. Das hat alles soweit gepaßt.
Was ich jedoch noch nicht gemacht hatte war in der httpd.conf das Umschreiben der URL in der Verzeichnis zu erlauben. 
AllowOverride None  -->  AllowOverride FileInfo
Danach ging es wie erwartet. Hmmm doof....
Vielen Lieben Dank für dein Bemühen.
LG
Mike

**Comment by tkrebs** [comment]
Danke für deine Rückmeldung. Damit sollten sich nun alle mod_rewrite-Probleme lösen lassen.

Grüße
Tobias

**Comment by liebla** [comment]
Hallo 
ich suche verzweifelt nach einer Lösung für mein Buchungssystem... ich denke die Lösüng liegt evtl. in AllowOverride None --> AllowOverride FileInfo... nur weiß ich nicht in welcher Datei ich dies ändern kann. 
Bei mir wird nach dem Kalender nichts mehr angezeigt. Keine Fehlermeldung. Nur eine weiße Seite. Dabei ist es egal auf welchen Button ich klicke ( Anmelden oder Buchungszeit), Ich bemerke immer nur, dass der Link nicht stimmt.
Ich hoffe, mit kann jemand helfen.
Gruß Anja

**Comment by tkrebs** [comment]
Das ist richtig, AllowOverride legt fest, welche Einstellungsmöglichkeiten in den einzelnen .htaccess-Dateien der Webseiten erlaubt sind. Wenn dies auf None steht, kann das Buchungssystem sich nicht richtig konfigurieren und funktioniert nicht. Das kann leider nur in der zentralen Konfigurationsdatei des Apache-Webservers eingestellt werden und ist auf gemieteten (meist günstigen) Shared-Hosting-Servern leider praktisch nicht änderbar.

**Comment by liebla** [comment]
Vielen Dank für die schnelle Antwort.

**Comment by mjmpeace** [comment]
> Versuche mal testweise, die komplette Datei
> 
> `/public/.htaccess`
> 
> mit folgendem Inhalt zu ersetzen:
> 
> ```
> <IfModule mod_rewrite.c>
> 
>     RewriteEngine On
> 
>     RewriteRule ^(favicon\.ico)$ imgs-client/icons/fav.ico [L]
>     RewriteRule ^(robots\.txt)$ misc/$1 [L]
> 
>     RewriteCond %{REQUEST_FILENAME} -s [OR]
>     RewriteCond %{REQUEST_FILENAME} -l [OR]
>     RewriteCond %{REQUEST_FILENAME} -d
>     RewriteRule ^.*$ - [NC,L]
> 
>     RewriteCond %{REQUEST_URI}::$1 ^(/.+)(.+)::\2$
>     RewriteRule ^(.*) - [E=BASE:%1]
>     RewriteRule ^(.*)$ %{ENV:BASE}index.php [NC,L]
> 
> </IfModule>
> ```

Das war bei mir auch die Lösung für das Problem.

**Comment by holgerbusch** [comment]
> <IfModule mod_rewrite.c>
> 
>     RewriteEngine On
> 
>     RewriteRule ^(favicon\.ico)$ imgs-client/icons/fav.ico [L]
>     RewriteRule ^(robots\.txt)$ misc/$1 [L]
> 
>     RewriteCond %{REQUEST_FILENAME} -s [OR]
>     RewriteCond %{REQUEST_FILENAME} -l [OR]
>     RewriteCond %{REQUEST_FILENAME} -d
>     RewriteRule ^.*$ - [NC,L]
> 
>     RewriteCond %{REQUEST_URI}::$1 ^(/.+)(.+)::\2$
>     RewriteRule ^(.*) - [E=BASE:%1]
>     RewriteRule ^(.*)$ %{ENV:BASE}index.php [NC,L]
> 
> </IfModule>


Dies habe ich gerade bei meiner Installation bei 1und1/ionos gemacht - ohne Erfolg.
Die Seite kann geöffnet werden, aber bei den Links kommt ein Internal Server Error

**Comment by mjmpeace** [comment]
Ich kann mich erinnern, dass ich ein ähnliches Problem beim Ausetzen des Systems hatte. Ich muss gucken. Meine aber, dass der Provider etwas in den PHP Einstellungen gemacht hat und Tobias auch eine Änderung in einer Datei oder so gemacht hat. Ich gucke später. Mein PC muss wieder aufgebaut werden. Michael Von meinem Samsung Galaxy Smartphone gesendet.
-------- Ursprüngliche Nachricht --------Von: holgerbusch <notifications@github.com> Datum: 26.04.20  16:24  (GMT+01:00) An: tkrebs/ep3-bs <ep3-bs@noreply.github.com> Cc: mjmpeace <friede@m-peace.de>, Comment <comment@noreply.github.com> Betreff: Re: [tkrebs/ep3-bs] Bei anmeldung wird die Seite nicht gefunden (#12) 





RewriteEngine On



RewriteRule ^(favicon\.ico)$ imgs-client/icons/fav.ico [L]

RewriteRule ^(robots\.txt)$ misc/$1 [L]



RewriteCond %{REQUEST_FILENAME} -s [OR]

RewriteCond %{REQUEST_FILENAME} -l [OR]

RewriteCond %{REQUEST_FILENAME} -d

RewriteRule ^.*$ - [NC,L]



RewriteCond %{REQUEST_URI}::$1 ^(/.+)(.+)::\2$

RewriteRule ^(.*) - [E=BASE:%1]

RewriteRule ^(.*)$ %{ENV:BASE}index.php [NC,L]







Dies habe ich gerade bei meiner Installation bei 1und1/ionos gemacht - ohne Erfolg.

Die Seite kann geöffnet werden, aber bei den Links kommt ein Internal Server Error



—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/tkrebs/ep3-bs/issues/12#issuecomment-619559589",

"url": "https://github.com/tkrebs/ep3-bs/issues/12#issuecomment-619559589",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by mjmpeace** [comment]
Eventuell ist es dieser Fehler:

Die php.ini muss entsprechend angepasst werden, damit das Modul intl aktiviert wird.

 

Michael

 

Von: holgerbusch [mailto:notifications@github.com] 
Gesendet: Sonntag, 26. April 2020 16:25
An: tkrebs/ep3-bs <ep3-bs@noreply.github.com>
Cc: mjmpeace <friede@m-peace.de>; Comment <comment@noreply.github.com>
Betreff: Re: [tkrebs/ep3-bs] Bei anmeldung wird die Seite nicht gefunden (#12)

 

RewriteEngine On
 
 
 
RewriteRule ^(favicon\.ico)$ imgs-client/icons/fav.ico [L]
 
RewriteRule ^(robots\.txt)$ misc/$1 [L]
 
 
 
RewriteCond %{REQUEST_FILENAME} -s [OR]
 
RewriteCond %{REQUEST_FILENAME} -l [OR]
 
RewriteCond %{REQUEST_FILENAME} -d
 
RewriteRule ^.*$ - [NC,L]
 
 
 
RewriteCond %{REQUEST_URI}::$1 ^(/.+)(.+)::\2$
 
RewriteRule ^(.*) - [E=BASE:%1]
 
RewriteRule ^(.*)$ %{ENV:BASE}index.php [NC,L]
 

Dies habe ich gerade bei meiner Installation bei 1und1/ionos gemacht - ohne Erfolg.
Die Seite kann geöffnet werden, aber bei den Links kommt ein Internal Server Error

**Comment by holgerbusch** [comment]
Hey. Die habe ich angepasst. 
Ich nehme an es liegt an der httpd.conf aber da komme bei 1und1 ja nicht dran. 

Auf xampp läuft es...


Lieben Gruß
Holger Busch

**Comment by mjmpeace** [comment]
Dann wende dich an den 1und1 Support – die helfen sehr gut.

 

Von: holgerbusch [mailto:notifications@github.com] 
Gesendet: Sonntag, 26. April 2020 19:30
An: tkrebs/ep3-bs <ep3-bs@noreply.github.com>
Cc: mjmpeace <friede@m-peace.de>; Comment <comment@noreply.github.com>
Betreff: Re: [tkrebs/ep3-bs] Bei anmeldung wird die Seite nicht gefunden (#12)

 

Hey. Die habe ich angepasst. 
Ich nehme an es liegt an der httpd.conf aber da komme bei 1und1 ja nicht dran. 

Auf xampp läuft es...


Lieben Gruß
Holger Busch

**Comment by holgerbusch** [comment]
Ok. Die Frage ist nur was konkret muss ich denen sagen, was sie tun sollen...?

Lieben Gruß
Holger Busch

**Comment by mjmpeace** [comment]
Die kennen sich mit solchen Problem aus. Erkläre das Problem so, wie es besteht.

Dann werden die wissen, was zu tun ist.

 

Michael

 

Von: holgerbusch [mailto:notifications@github.com] 
Gesendet: Sonntag, 26. April 2020 20:05
An: tkrebs/ep3-bs <ep3-bs@noreply.github.com>
Cc: mjmpeace <friede@m-peace.de>; Comment <comment@noreply.github.com>
Betreff: Re: [tkrebs/ep3-bs] Bei anmeldung wird die Seite nicht gefunden (#12)

 

Ok. Die Frage ist nur was konkret muss ich denen sagen, was sie tun sollen...?

Lieben Gruß
Holger Busch

**Comment by holgerbusch** [comment]
> Die kennen sich mit solchen Problem aus. Erkläre das Problem so, wie es besteht. Dann werden die wissen, was zu tun ist. Michael 

Hi Michael, ich habe bei 1und1 angerufen und habe die Info bekommen, dass keine Änderungen an der httpd.conf für den Webserver gemacht werden.
Somit kann ich AllowOverride None nicht in AllowOverride FileInfo ändern.

Man hat mir 5 Mal gesagt, das was ich machen kann ist über die htaccess arbeiten.
Ich habe versucht zu erklären, dass das nichts nützt wenn in der httpd.conf das AllowOveride auf None steht - aber ich komme da nicht weiter. 
An der httpd.conf oder an der php.ini wird seitens 1und1 nichts geändert.

**Comment by liebla** [comment]
Hallo zusammen
Ich bin hier in CC gesetzt. Ich denke das ist keine Absicht😂

Am 27. April 2020 12:30:38 schrieb holgerbusch <notifications@github.com>:
>
> Die kennen sich mit solchen Problem aus. Erkläre das Problem so, wie es 
> besteht. Dann werden die wissen, was zu tun ist. Michael
> Hi Michael, ich habe bei 1und1 angerufen und habe die Info bekommen, dass 
> keine Änderungen an der httpd.conf für den Webserver gemacht werden.
> Somit kann ich AllowOverride None nicht in AllowOverride FileInfo 
> ändern.Man hat mir 5 Mal gesagt, das was ich machen kann ist über die 
> htaccess arbeiten.
> Ich habe versucht zu erklären, dass das nichts nützt wenn in der httpd.conf 
> das AllowOveride auf None steht - aber ich komme da nicht weiter.
> An der httpd.conf oder an der php.ini wird seitens 1und1 nichts geändert.—
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or unsubscribe.


Mit AquaMail Android
https://www.mobisystems.com/aqua-mail

**Comment by mjmpeace** [comment]
Dann kannst du nur den Tobias fragen nach Alternativen.Michael Von meinem Samsung Galaxy Smartphone gesendet.
-------- Ursprüngliche Nachricht --------Von: holgerbusch <notifications@github.com> Datum: 27.04.20  12:30  (GMT+01:00) An: tkrebs/ep3-bs <ep3-bs@noreply.github.com> Cc: mjmpeace <friede@m-peace.de>, Comment <comment@noreply.github.com> Betreff: Re: [tkrebs/ep3-bs] Bei anmeldung wird die Seite nicht gefunden (#12) 



Die kennen sich mit solchen Problem aus. Erkläre das Problem so, wie es besteht. Dann werden die wissen, was zu tun ist. Michael



Hi Michael, ich habe bei 1und1 angerufen und habe die Info bekommen, dass keine Änderungen an der httpd.conf für den Webserver gemacht werden.

Somit kann ich AllowOverride None nicht in AllowOverride FileInfo ändern.

Man hat mir 5 Mal gesagt, das was ich machen kann ist über die htaccess arbeiten.

Ich habe versucht zu erklären, dass das nichts nützt wenn in der httpd.conf das AllowOveride auf None steht - aber ich komme da nicht weiter.

An der httpd.conf oder an der php.ini wird seitens 1und1 nichts geändert.



—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/tkrebs/ep3-bs/issues/12#issuecomment-619890045",

"url": "https://github.com/tkrebs/ep3-bs/issues/12#issuecomment-619890045",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]
