### ISSUE TITLE
URL not working except home page.

### ISSUE THREAD

**Issue by roshanapptec** [tkrebs/ep3-bs#186]
Hi, I have installed it using composer in xampp server. Home page is working fine but when I click on other links like register/login it shows error 404 not found. 
Thanks

**Comment by tkrebs** [comment]
You need to enable the Apache module "mod_rewrite" so that virtual directories like "user" will work.

**Comment by roshanapptec** [comment]
it is already enabled in my apache "httpd.conf". Or it needs to be enabled on other project pages.

**Comment by buckl97** [comment]
I am having this problem also, have you managed to solve it?

**Comment by buckl97** [comment]
The error is: Object not found!
The requested URL was not found on this server. The link on the referring page seems to be wrong or outdated. Please inform the author of that page about the error. If you think this is a server error, please contact the webmaster.
Error 404

**Comment by tkrebs** [comment]
Perhaps this helps:

https://stackoverflow.com/a/31961430

**Comment by buckl97** [comment]
I have fixed this problem, check that the file .htaccess_original found at public/ is changed to .htaccess

**Comment by obel1x** [comment]
for me, followsymlinks was turned off in server-config, also leading to 404 and erro msg in apache:
AH00670: Options FollowSymLinks and SymLinksIfOwnerMatch are both off, so the RewriteRule directive is also forbidden due to its similar ability to circumvent directory restrictions : /srv/www...

so check out, that your server has:
<Directory "/srv/www/ep3">
    Options FollowSymLinks
    AllowOverride All
</Directory>
