### ISSUE TITLE
Emails for registration

### ISSUE THREAD

**Issue by buckl97** [tkrebs/ep3-bs#194]
Hi there, I am getting an error when I try register a new user. 

<img width="934" alt="capture" src="https://user-images.githubusercontent.com/43755084/50782545-3bde4300-12a0-11e9-8ba6-2abe3235c7b6.PNG">
<img width="584" alt="capture1" src="https://user-images.githubusercontent.com/43755084/50782549-400a6080-12a0-11e9-85cc-2a6ff5b8e721.PNG">

I have edited the php.ini and sendmail.ini files to enable emails but I keep getting the same. Im wondering if anyone else has had this problem or has an ideas on how to fix it.

Thanks, 
Liam

**Comment by tkrebs** [comment]
The deprecation warnings should be fixed in the latest version of the underlying Zend Framework 2, available by either downloading the latest version from our website or alternatively running a composer update.

The problem with emails not beeing sent looks like a configuration issue. I know from experience that email configuration for PHP can sometimes be lots of trial and error.
