### ISSUE TITLE
Adding online payments for squares

### ISSUE THREAD

**Issue by Buckley97** [tkrebs/ep3-bs#202]
Hello,

I am trying to add online payments using Stripe. I am trying to pass the value in $priceSummary from the confirmation.phtml page to the stripe checkout page and charge the customer. Maybe I am using the wrong variable or looking in the wrong place. I am currently trying to do this using sessions. Do you know if $priceSummary is the correct variable to use or should I try something else. Hope this makes sense.

Regards

**Comment by tkrebs** [comment]
The `$pricingSummary` contains a HTML string. However, you need the final price as a raw number.

As you can see in the view helper that generates the pricing summary, the calculation of the final price consists of the price for the booking itself:

https://github.com/tkrebs/ep3-bs/blob/master/module/Square/src/Square/View/Helper/PricingSummary.php#L36

Plus the price of each additional product, if any:

https://github.com/tkrebs/ep3-bs/blob/master/module/Square/src/Square/View/Helper/PricingSummary.php#L76

Unfortunately, during the confirmation, there is no variable yet holding this number, since there (currently) is no external checkout. We are working to improve that soon, but for now, you would have to write your own little helper service to get the total price.

**Comment by Buckley97** [comment]
<img width="472" alt="confirmation" src="https://user-images.githubusercontent.com/43447311/53239608-57f14480-3694-11e9-9f3e-647357d08af5.PNG">

<img width="229" alt="checkout" src="https://user-images.githubusercontent.com/43447311/53240274-35602b00-3696-11e9-8ec6-a86cd8c27515.PNG">

As I am not familiar with helper services, do you think there is any other way to create the summary (total/final) price circled in image 1 and post it in a checkout form so that the default value circled in image 2 will match. When the "complete booking" button is clicked, the user is brought to the checkout page but my issue is that I am not sure how to match the value of $50 with the total booking price of 20.

**Comment by tkrebs** [comment]
I don't think there is another way to get the total price during the checkout other than calculating it yourself using the above mentioned example.

**Comment by Buckley97** [comment]
Ok ill give it a try, thanks for your help.
